# -*- coding: utf-8 -*-
"""UI text for claw_tray.py in ten languages.

STRINGS: short menu, tooltip and notification texts (title case is applied at load by claw_tray).
HELP: what every setting does, shown from the Help submenu and in the guide window.
PRESET_NAMES: default names of the five presets.
Placeholders like {lvl}, {dpi}, {n}, {name} must be kept as they are.
"""

LANG_NAMES = {
    "tr": "Türkçe", "en": "English", "es": "Español", "fr": "Français", "de": "Deutsch",
    "ru": "Русский", "zh": "中文", "ja": "日本語", "ko": "한국어", "ar": "العربية",
}

# Windows primary language id (GetUserDefaultUILanguage & 0x3FF) to our code
WIN_LANG_IDS = {0x1F: "tr", 0x09: "en", 0x0A: "es", 0x0C: "fr", 0x07: "de",
                0x19: "ru", 0x04: "zh", 0x11: "ja", 0x12: "ko", 0x01: "ar"}

RTL = {"ar"}

PRESET_NAMES = {
    "tr": ["Oyun", "Masaüstü", "Hassas", "Pil Tasarrufu", "Sunum"],
    "en": ["Gaming", "Desktop", "Precision", "Battery Saver", "Presentation"],
    "es": ["Juegos", "Escritorio", "Precisión", "Ahorro de batería", "Presentación"],
    "fr": ["Jeu", "Bureau", "Précision", "Économie de batterie", "Présentation"],
    "de": ["Spielen", "Desktop", "Präzision", "Energiesparen", "Präsentation"],
    "ru": ["Игры", "Рабочий стол", "Точность", "Экономия батареи", "Презентация"],
    "zh": ["游戏", "桌面", "精确", "省电", "演示"],
    "ja": ["ゲーム", "デスクトップ", "精密", "省電力", "プレゼン"],
    "ko": ["게임", "데스크톱", "정밀", "배터리 절약", "프레젠테이션"],
    "ar": ["ألعاب", "سطح المكتب", "دقة", "توفير البطارية", "عرض تقديمي"],
}

STRINGS = {
    "tr": {
        "app": "Claw fare",
        "title_paused": "Claw fare: CrossFire açık, duraklatıldı",
        "title_asleep": "Claw fare: uykuda (hareket ettirin)",
        "title_ok": "Claw fare: %{lvl}",
        "charging": " (şarj oluyor)",
        "dpi_suffix": ", {dpi} DPI",
        "n_charge_on": "Şarj başladı (%{lvl})",
        "n_charge_off": "Şarj kablosu çıktı (%{lvl})",
        "n_full": "Pil doldu (%100), kabloyu çıkarabilirsiniz",
        "n_low": "Pil %{lvl}, şarj edin",
        "n_write_fail": "Ayar yazılamadı: fare uykuda ya da CrossFire açık olabilir",
        "n_preset": "{name} ön ayarı uygulandı ({dpi} DPI)",
        "presets": "Ön ayarlar", "apply": "Uygula", "save_here": "Mevcut ayarları buraya kaydet",
        "rename": "Yeniden adlandır", "reset_preset": "Varsayılana döndür",
        "n_saved": "Mevcut ayarlar {name} ön ayarına kaydedildi", "rename_title": "Ön ayar adı", "rename_prompt": "Yeni ad:",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "Aktif kademe", "stage_n": "Kademe {n}: {dpi} DPI",
        "stage_value": "Kademe {n} değeri ({dpi})", "stage_count": "Kademe sayısı",
        "rate": "Rapor hızı", "debounce": "Debounce", "ms": "{n} ms",
        "sensor": "Sensör", "motion": "Motion sync", "angle": "Açı düzeltme (angle snapping)",
        "ripple": "Ripple kontrolü", "perf": "Maksimum performans", "off": "Kapalı",
        "sec": "{n} sn", "min": "{n} dk",
        "light": "Işık", "mode": "Mod", "color": "Renk", "brightness": "Parlaklık", "speed": "Hız",
        "moveoff": "Hareket ederken ışığı kapat", "ledoff": "Hareketsiz kalınca kapanma süresi",
        "dpiled": "DPI gösterge ışığı",
        "led1": "Gökkuşağı akış", "led2": "Tek renk nefes", "led3": "Gökkuşağı sabit",
        "led4": "Neon", "led5": "Gökkuşağı yanıp sönme", "led6": "Çok renkli sabit",
        "dl1": "Sabit ışık", "dl2": "Yanıp sönme",
        "red": "Kırmızı", "green": "Yeşil", "blue": "Mavi", "white": "Beyaz", "purple": "Mor",
        "cyan": "Turkuaz", "yellow": "Sarı", "orange": "Turuncu", "pink": "Pembe",
        "longrange": "Uzun menzil modu", "language": "Dil",
        "refresh": "Şimdi yenile", "quit": "Çıkış",
        "help": "Yardım", "guide": "Rehberi aç", "guide_title": "Claw fare rehberi", "battery": "Pil göstergesi",
    },
    "en": {
        "app": "Claw mouse",
        "title_paused": "Claw mouse: CrossFire is running, paused",
        "title_asleep": "Claw mouse: asleep (move it)",
        "title_ok": "Claw mouse: {lvl}%",
        "charging": " (charging)",
        "dpi_suffix": ", {dpi} DPI",
        "n_charge_on": "Charging started ({lvl}%)",
        "n_charge_off": "Charging cable unplugged ({lvl}%)",
        "n_full": "Battery full (100%), you can unplug the cable",
        "n_low": "Battery {lvl}%, please charge",
        "n_write_fail": "Could not write the setting: mouse asleep or CrossFire running",
        "n_preset": "{name} preset applied ({dpi} DPI)",
        "presets": "Presets", "apply": "Apply", "save_here": "Save current settings here",
        "rename": "Rename", "reset_preset": "Reset to default",
        "n_saved": "Current settings saved to preset {name}", "rename_title": "Preset name", "rename_prompt": "New name:",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "Active stage", "stage_n": "Stage {n}: {dpi} DPI",
        "stage_value": "Stage {n} value ({dpi})", "stage_count": "Number of stages",
        "rate": "Report rate", "debounce": "Debounce", "ms": "{n} ms",
        "sensor": "Sensor", "motion": "Motion sync", "angle": "Angle snapping",
        "ripple": "Ripple control", "perf": "Peak performance", "off": "Off",
        "sec": "{n} s", "min": "{n} min",
        "light": "Lighting", "mode": "Mode", "color": "Colour", "brightness": "Brightness", "speed": "Speed",
        "moveoff": "Lights off while moving", "ledoff": "Lights off delay when idle",
        "dpiled": "DPI indicator light",
        "led1": "Rainbow wave", "led2": "Single colour breathing", "led3": "Rainbow fixed",
        "led4": "Neon", "led5": "Rainbow flicker", "led6": "Multicolour fixed",
        "dl1": "Steady", "dl2": "Flicker",
        "red": "Red", "green": "Green", "blue": "Blue", "white": "White", "purple": "Purple",
        "cyan": "Cyan", "yellow": "Yellow", "orange": "Orange", "pink": "Pink",
        "longrange": "Long range mode", "language": "Language",
        "refresh": "Refresh now", "quit": "Quit",
        "help": "Help", "guide": "Open guide", "guide_title": "Claw mouse guide", "battery": "Battery indicator",
    },
    "es": {
        "app": "Ratón Claw",
        "title_paused": "Ratón Claw: CrossFire en ejecución, en pausa",
        "title_asleep": "Ratón Claw: en reposo (muévelo)",
        "title_ok": "Ratón Claw: {lvl}%",
        "charging": " (cargando)",
        "dpi_suffix": ", {dpi} DPI",
        "n_charge_on": "Carga iniciada ({lvl}%)",
        "n_charge_off": "Cable de carga desconectado ({lvl}%)",
        "n_full": "Batería llena (100%), puedes desconectar el cable",
        "n_low": "Batería al {lvl}%, carga el ratón",
        "n_write_fail": "No se pudo escribir el ajuste: ratón en reposo o CrossFire en ejecución",
        "n_preset": "Preajuste {name} aplicado ({dpi} DPI)",
        "presets": "Preajustes", "apply": "Aplicar", "save_here": "Guardar los ajustes actuales aquí",
        "rename": "Renombrar", "reset_preset": "Restablecer valores predeterminados",
        "n_saved": "Ajustes actuales guardados en el preajuste {name}", "rename_title": "Nombre del preajuste", "rename_prompt": "Nuevo nombre:",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "Nivel activo", "stage_n": "Nivel {n}: {dpi} DPI",
        "stage_value": "Valor del nivel {n} ({dpi})", "stage_count": "Número de niveles",
        "rate": "Tasa de sondeo", "debounce": "Antirrebote", "ms": "{n} ms",
        "sensor": "Sensor", "motion": "Motion sync", "angle": "Corrección de ángulo",
        "ripple": "Control de ondulación", "perf": "Rendimiento máximo", "off": "Apagado",
        "sec": "{n} s", "min": "{n} min",
        "light": "Iluminación", "mode": "Modo", "color": "Color", "brightness": "Brillo", "speed": "Velocidad",
        "moveoff": "Apagar luces al mover", "ledoff": "Retardo de apagado en reposo",
        "dpiled": "Luz indicadora de DPI",
        "led1": "Onda arcoíris", "led2": "Respiración de un color", "led3": "Arcoíris fijo",
        "led4": "Neón", "led5": "Parpadeo arcoíris", "led6": "Multicolor fijo",
        "dl1": "Fija", "dl2": "Parpadeo",
        "red": "Rojo", "green": "Verde", "blue": "Azul", "white": "Blanco", "purple": "Morado",
        "cyan": "Cian", "yellow": "Amarillo", "orange": "Naranja", "pink": "Rosa",
        "longrange": "Modo de largo alcance", "language": "Idioma",
        "refresh": "Actualizar ahora", "quit": "Salir",
        "help": "Ayuda", "guide": "Abrir la guía", "guide_title": "Guía del ratón Claw", "battery": "Indicador de batería",
    },
    "fr": {
        "app": "Souris Claw",
        "title_paused": "Souris Claw : CrossFire en cours, en pause",
        "title_asleep": "Souris Claw : en veille (bougez la)",
        "title_ok": "Souris Claw : {lvl}%",
        "charging": " (en charge)",
        "dpi_suffix": ", {dpi} DPI",
        "n_charge_on": "Charge commencée ({lvl}%)",
        "n_charge_off": "Câble de charge débranché ({lvl}%)",
        "n_full": "Batterie pleine (100%), vous pouvez débrancher le câble",
        "n_low": "Batterie à {lvl}%, rechargez la souris",
        "n_write_fail": "Impossible d'écrire le réglage : souris en veille ou CrossFire en cours",
        "n_preset": "Préréglage {name} appliqué ({dpi} DPI)",
        "presets": "Préréglages", "apply": "Appliquer", "save_here": "Enregistrer les réglages actuels ici",
        "rename": "Renommer", "reset_preset": "Rétablir la valeur par défaut",
        "n_saved": "Réglages actuels enregistrés dans le préréglage {name}", "rename_title": "Nom du préréglage", "rename_prompt": "Nouveau nom :",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "Niveau actif", "stage_n": "Niveau {n} : {dpi} DPI",
        "stage_value": "Valeur du niveau {n} ({dpi})", "stage_count": "Nombre de niveaux",
        "rate": "Taux de rapport", "debounce": "Anti rebond", "ms": "{n} ms",
        "sensor": "Capteur", "motion": "Motion sync", "angle": "Correction d'angle",
        "ripple": "Contrôle d'ondulation", "perf": "Performance maximale", "off": "Désactivé",
        "sec": "{n} s", "min": "{n} min",
        "light": "Éclairage", "mode": "Mode", "color": "Couleur", "brightness": "Luminosité", "speed": "Vitesse",
        "moveoff": "Éteindre les lumières en mouvement", "ledoff": "Délai d'extinction au repos",
        "dpiled": "Voyant DPI",
        "led1": "Vague arc en ciel", "led2": "Respiration monochrome", "led3": "Arc en ciel fixe",
        "led4": "Néon", "led5": "Scintillement arc en ciel", "led6": "Multicolore fixe",
        "dl1": "Fixe", "dl2": "Clignotant",
        "red": "Rouge", "green": "Vert", "blue": "Bleu", "white": "Blanc", "purple": "Violet",
        "cyan": "Cyan", "yellow": "Jaune", "orange": "Orange", "pink": "Rose",
        "longrange": "Mode longue portée", "language": "Langue",
        "refresh": "Actualiser maintenant", "quit": "Quitter",
        "help": "Aide", "guide": "Ouvrir le guide", "guide_title": "Guide de la souris Claw", "battery": "Indicateur de batterie",
    },
    "de": {
        "app": "Claw Maus",
        "title_paused": "Claw Maus: CrossFire läuft, pausiert",
        "title_asleep": "Claw Maus: im Ruhezustand (bewegen)",
        "title_ok": "Claw Maus: {lvl}%",
        "charging": " (lädt)",
        "dpi_suffix": ", {dpi} DPI",
        "n_charge_on": "Laden gestartet ({lvl}%)",
        "n_charge_off": "Ladekabel getrennt ({lvl}%)",
        "n_full": "Akku voll (100%), das Kabel kann getrennt werden",
        "n_low": "Akku bei {lvl}%, bitte laden",
        "n_write_fail": "Einstellung konnte nicht geschrieben werden: Maus im Ruhezustand oder CrossFire läuft",
        "n_preset": "Voreinstellung {name} angewendet ({dpi} DPI)",
        "presets": "Voreinstellungen", "apply": "Anwenden", "save_here": "Aktuelle Einstellungen hier speichern",
        "rename": "Umbenennen", "reset_preset": "Auf Standard zurücksetzen",
        "n_saved": "Aktuelle Einstellungen in Voreinstellung {name} gespeichert", "rename_title": "Name der Voreinstellung", "rename_prompt": "Neuer Name:",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "Aktive Stufe", "stage_n": "Stufe {n}: {dpi} DPI",
        "stage_value": "Wert der Stufe {n} ({dpi})", "stage_count": "Anzahl der Stufen",
        "rate": "Abfragerate", "debounce": "Entprellung", "ms": "{n} ms",
        "sensor": "Sensor", "motion": "Motion Sync", "angle": "Winkelkorrektur",
        "ripple": "Ripple Kontrolle", "perf": "Maximale Leistung", "off": "Aus",
        "sec": "{n} s", "min": "{n} Min",
        "light": "Beleuchtung", "mode": "Modus", "color": "Farbe", "brightness": "Helligkeit", "speed": "Geschwindigkeit",
        "moveoff": "Licht bei Bewegung aus", "ledoff": "Abschaltverzögerung im Leerlauf",
        "dpiled": "DPI Anzeigelicht",
        "led1": "Regenbogenwelle", "led2": "Einfarbig atmend", "led3": "Regenbogen fest",
        "led4": "Neon", "led5": "Regenbogen flackernd", "led6": "Mehrfarbig fest",
        "dl1": "Dauerhaft", "dl2": "Flackern",
        "red": "Rot", "green": "Grün", "blue": "Blau", "white": "Weiß", "purple": "Lila",
        "cyan": "Cyan", "yellow": "Gelb", "orange": "Orange", "pink": "Rosa",
        "longrange": "Langstreckenmodus", "language": "Sprache",
        "refresh": "Jetzt aktualisieren", "quit": "Beenden",
        "help": "Hilfe", "guide": "Anleitung öffnen", "guide_title": "Claw Maus Anleitung", "battery": "Akkuanzeige",
    },
    "ru": {
        "app": "Мышь Claw",
        "title_paused": "Мышь Claw: запущен CrossFire, пауза",
        "title_asleep": "Мышь Claw: спит (подвигайте её)",
        "title_ok": "Мышь Claw: {lvl}%",
        "charging": " (заряжается)",
        "dpi_suffix": ", {dpi} DPI",
        "n_charge_on": "Зарядка началась ({lvl}%)",
        "n_charge_off": "Кабель зарядки отключён ({lvl}%)",
        "n_full": "Батарея заряжена (100%), кабель можно отключить",
        "n_low": "Заряд {lvl}%, зарядите мышь",
        "n_write_fail": "Не удалось записать настройку: мышь спит или запущен CrossFire",
        "n_preset": "Пресет {name} применён ({dpi} DPI)",
        "presets": "Пресеты", "apply": "Применить", "save_here": "Сохранить текущие настройки сюда",
        "rename": "Переименовать", "reset_preset": "Сбросить по умолчанию",
        "n_saved": "Текущие настройки сохранены в пресет {name}", "rename_title": "Имя пресета", "rename_prompt": "Новое имя:",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "Активный уровень", "stage_n": "Уровень {n}: {dpi} DPI",
        "stage_value": "Значение уровня {n} ({dpi})", "stage_count": "Число уровней",
        "rate": "Частота опроса", "debounce": "Антидребезг", "ms": "{n} мс",
        "sensor": "Сенсор", "motion": "Motion Sync", "angle": "Выравнивание угла",
        "ripple": "Контроль ряби", "perf": "Максимальная производительность", "off": "Выкл",
        "sec": "{n} с", "min": "{n} мин",
        "light": "Подсветка", "mode": "Режим", "color": "Цвет", "brightness": "Яркость", "speed": "Скорость",
        "moveoff": "Гасить подсветку при движении", "ledoff": "Задержка выключения в простое",
        "dpiled": "Индикатор DPI",
        "led1": "Радужная волна", "led2": "Одноцветное дыхание", "led3": "Радуга статичная",
        "led4": "Неон", "led5": "Радужное мерцание", "led6": "Многоцветная статичная",
        "dl1": "Постоянно", "dl2": "Мерцание",
        "red": "Красный", "green": "Зелёный", "blue": "Синий", "white": "Белый", "purple": "Фиолетовый",
        "cyan": "Голубой", "yellow": "Жёлтый", "orange": "Оранжевый", "pink": "Розовый",
        "longrange": "Режим дальней связи", "language": "Язык",
        "refresh": "Обновить сейчас", "quit": "Выход",
        "help": "Справка", "guide": "Открыть руководство", "guide_title": "Руководство по мыши Claw", "battery": "Индикатор батареи",
    },
    "zh": {
        "app": "Claw 鼠标",
        "title_paused": "Claw 鼠标：CrossFire 正在运行，已暂停",
        "title_asleep": "Claw 鼠标：休眠中（请移动鼠标）",
        "title_ok": "Claw 鼠标：{lvl}%",
        "charging": "（充电中）",
        "dpi_suffix": "，{dpi} DPI",
        "n_charge_on": "开始充电（{lvl}%）",
        "n_charge_off": "充电线已拔出（{lvl}%）",
        "n_full": "电池已充满（100%），可以拔掉充电线",
        "n_low": "电量 {lvl}%，请充电",
        "n_write_fail": "无法写入设置：鼠标休眠或 CrossFire 正在运行",
        "n_preset": "已应用预设 {name}（{dpi} DPI）",
        "presets": "预设", "apply": "应用", "save_here": "将当前设置保存到此处",
        "rename": "重命名", "reset_preset": "恢复默认",
        "n_saved": "当前设置已保存到预设 {name}", "rename_title": "预设名称", "rename_prompt": "新名称：",
        "preset_label": "{name}（{dpi} DPI）",
        "dpi": "DPI", "active_stage": "当前档位", "stage_n": "档位 {n}：{dpi} DPI",
        "stage_value": "档位 {n} 数值（{dpi}）", "stage_count": "档位数量",
        "rate": "回报率", "debounce": "去抖动", "ms": "{n} ms",
        "sensor": "传感器", "motion": "运动同步", "angle": "直线修正",
        "ripple": "波纹控制", "perf": "最高性能", "off": "关闭",
        "sec": "{n} 秒", "min": "{n} 分钟",
        "light": "灯光", "mode": "模式", "color": "颜色", "brightness": "亮度", "speed": "速度",
        "moveoff": "移动时关闭灯光", "ledoff": "静止后关灯延时",
        "dpiled": "DPI 指示灯",
        "led1": "彩虹流动", "led2": "单色呼吸", "led3": "彩虹常亮",
        "led4": "霓虹", "led5": "彩虹闪烁", "led6": "多色常亮",
        "dl1": "常亮", "dl2": "闪烁",
        "red": "红色", "green": "绿色", "blue": "蓝色", "white": "白色", "purple": "紫色",
        "cyan": "青色", "yellow": "黄色", "orange": "橙色", "pink": "粉色",
        "longrange": "远距离模式", "language": "语言",
        "refresh": "立即刷新", "quit": "退出",
        "help": "帮助", "guide": "打开指南", "guide_title": "Claw 鼠标指南", "battery": "电池指示",
    },
    "ja": {
        "app": "Claw マウス",
        "title_paused": "Claw マウス：CrossFire 実行中、一時停止",
        "title_asleep": "Claw マウス：スリープ中（動かしてください）",
        "title_ok": "Claw マウス：{lvl}%",
        "charging": "（充電中）",
        "dpi_suffix": "、{dpi} DPI",
        "n_charge_on": "充電を開始しました（{lvl}%）",
        "n_charge_off": "充電ケーブルが外れました（{lvl}%）",
        "n_full": "満充電（100%）、ケーブルを外せます",
        "n_low": "バッテリー {lvl}%、充電してください",
        "n_write_fail": "設定を書き込めません：マウスがスリープ中か CrossFire が実行中です",
        "n_preset": "プリセット {name} を適用しました（{dpi} DPI）",
        "presets": "プリセット", "apply": "適用", "save_here": "現在の設定をここに保存",
        "rename": "名前を変更", "reset_preset": "初期設定に戻す",
        "n_saved": "現在の設定をプリセット {name} に保存しました", "rename_title": "プリセット名", "rename_prompt": "新しい名前：",
        "preset_label": "{name}（{dpi} DPI）",
        "dpi": "DPI", "active_stage": "現在の段階", "stage_n": "段階 {n}：{dpi} DPI",
        "stage_value": "段階 {n} の値（{dpi}）", "stage_count": "段階数",
        "rate": "レポートレート", "debounce": "デバウンス", "ms": "{n} ms",
        "sensor": "センサー", "motion": "モーションシンク", "angle": "角度補正",
        "ripple": "リップル制御", "perf": "最高パフォーマンス", "off": "オフ",
        "sec": "{n} 秒", "min": "{n} 分",
        "light": "ライティング", "mode": "モード", "color": "色", "brightness": "明るさ", "speed": "速度",
        "moveoff": "移動中はライトを消す", "ledoff": "静止後の消灯までの時間",
        "dpiled": "DPI インジケーター",
        "led1": "レインボーウェーブ", "led2": "単色ブリージング", "led3": "レインボー固定",
        "led4": "ネオン", "led5": "レインボー点滅", "led6": "マルチカラー固定",
        "dl1": "常時点灯", "dl2": "点滅",
        "red": "赤", "green": "緑", "blue": "青", "white": "白", "purple": "紫",
        "cyan": "シアン", "yellow": "黄", "orange": "オレンジ", "pink": "ピンク",
        "longrange": "長距離モード", "language": "言語",
        "refresh": "今すぐ更新", "quit": "終了",
        "help": "ヘルプ", "guide": "ガイドを開く", "guide_title": "Claw マウス ガイド", "battery": "バッテリー表示",
    },
    "ko": {
        "app": "Claw 마우스",
        "title_paused": "Claw 마우스: CrossFire 실행 중, 일시 정지",
        "title_asleep": "Claw 마우스: 절전 중 (움직여 주세요)",
        "title_ok": "Claw 마우스: {lvl}%",
        "charging": " (충전 중)",
        "dpi_suffix": ", {dpi} DPI",
        "n_charge_on": "충전 시작 ({lvl}%)",
        "n_charge_off": "충전 케이블 분리됨 ({lvl}%)",
        "n_full": "배터리 충전 완료 (100%), 케이블을 분리해도 됩니다",
        "n_low": "배터리 {lvl}%, 충전하세요",
        "n_write_fail": "설정을 쓸 수 없습니다: 마우스가 절전 중이거나 CrossFire가 실행 중입니다",
        "n_preset": "프리셋 {name} 적용됨 ({dpi} DPI)",
        "presets": "프리셋", "apply": "적용", "save_here": "현재 설정을 여기에 저장",
        "rename": "이름 바꾸기", "reset_preset": "기본값으로 되돌리기",
        "n_saved": "현재 설정이 프리셋 {name}에 저장되었습니다", "rename_title": "프리셋 이름", "rename_prompt": "새 이름:",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "현재 단계", "stage_n": "단계 {n}: {dpi} DPI",
        "stage_value": "단계 {n} 값 ({dpi})", "stage_count": "단계 수",
        "rate": "폴링 레이트", "debounce": "디바운스", "ms": "{n} ms",
        "sensor": "센서", "motion": "모션 싱크", "angle": "각도 보정",
        "ripple": "리플 제어", "perf": "최고 성능", "off": "끔",
        "sec": "{n}초", "min": "{n}분",
        "light": "조명", "mode": "모드", "color": "색상", "brightness": "밝기", "speed": "속도",
        "moveoff": "움직일 때 조명 끄기", "ledoff": "정지 후 조명 꺼짐 지연",
        "dpiled": "DPI 표시등",
        "led1": "레인보우 웨이브", "led2": "단색 브리딩", "led3": "레인보우 고정",
        "led4": "네온", "led5": "레인보우 깜박임", "led6": "다색 고정",
        "dl1": "고정", "dl2": "깜박임",
        "red": "빨강", "green": "초록", "blue": "파랑", "white": "흰색", "purple": "보라",
        "cyan": "청록", "yellow": "노랑", "orange": "주황", "pink": "분홍",
        "longrange": "장거리 모드", "language": "언어",
        "refresh": "지금 새로 고침", "quit": "종료",
        "help": "도움말", "guide": "가이드 열기", "guide_title": "Claw 마우스 가이드", "battery": "배터리 표시",
    },
    "ar": {
        "app": "فأرة Claw",
        "title_paused": "فأرة Claw: CrossFire يعمل، متوقف مؤقتاً",
        "title_asleep": "فأرة Claw: في وضع السكون (حرّكها)",
        "title_ok": "فأرة Claw: {lvl}%",
        "charging": " (قيد الشحن)",
        "dpi_suffix": "، {dpi} DPI",
        "n_charge_on": "بدأ الشحن ({lvl}%)",
        "n_charge_off": "تم فصل كابل الشحن ({lvl}%)",
        "n_full": "البطارية ممتلئة (100%)، يمكنك فصل الكابل",
        "n_low": "البطارية {lvl}%، يرجى الشحن",
        "n_write_fail": "تعذّر كتابة الإعداد: الفأرة في وضع السكون أو CrossFire يعمل",
        "n_preset": "تم تطبيق الإعداد المسبق {name} ({dpi} DPI)",
        "presets": "الإعدادات المسبقة", "apply": "تطبيق", "save_here": "حفظ الإعدادات الحالية هنا",
        "rename": "إعادة تسمية", "reset_preset": "استعادة الافتراضي",
        "n_saved": "تم حفظ الإعدادات الحالية في الإعداد المسبق {name}", "rename_title": "اسم الإعداد المسبق", "rename_prompt": "الاسم الجديد:",
        "preset_label": "{name} ({dpi} DPI)",
        "dpi": "DPI", "active_stage": "المستوى النشط", "stage_n": "المستوى {n}: {dpi} DPI",
        "stage_value": "قيمة المستوى {n} ({dpi})", "stage_count": "عدد المستويات",
        "rate": "معدل الاستجابة", "debounce": "منع الارتداد", "ms": "{n} ms",
        "sensor": "المستشعر", "motion": "مزامنة الحركة", "angle": "تصحيح الزاوية",
        "ripple": "التحكم في التموج", "perf": "الأداء الأقصى", "off": "إيقاف",
        "sec": "{n} ث", "min": "{n} د",
        "light": "الإضاءة", "mode": "الوضع", "color": "اللون", "brightness": "السطوع", "speed": "السرعة",
        "moveoff": "إطفاء الإضاءة أثناء الحركة", "ledoff": "مهلة الإطفاء عند السكون",
        "dpiled": "مؤشر DPI",
        "led1": "موجة قوس قزح", "led2": "تنفّس بلون واحد", "led3": "قوس قزح ثابت",
        "led4": "نيون", "led5": "وميض قوس قزح", "led6": "متعدد الألوان ثابت",
        "dl1": "ثابت", "dl2": "وميض",
        "red": "أحمر", "green": "أخضر", "blue": "أزرق", "white": "أبيض", "purple": "بنفسجي",
        "cyan": "سماوي", "yellow": "أصفر", "orange": "برتقالي", "pink": "وردي",
        "longrange": "وضع المدى البعيد", "language": "اللغة",
        "refresh": "تحديث الآن", "quit": "خروج",
        "help": "مساعدة", "guide": "فتح الدليل", "guide_title": "دليل فأرة Claw", "battery": "مؤشر البطارية",
    },
}

# What each setting does. Shown as a notification from the Help submenu and in the guide window.
HELP = {
    "tr": [
        ("battery", "Simgedeki sayı pil yüzdesi, sarı çerçeve şarj olduğunu gösterir. Şarj başlayınca ve bitince, pil %20 ve %10'a düşünce bildirim gelir. Fare uykudayken simge gri olur, hareket ettirince düzelir."),
        ("presets", "Beş düzenlenebilir ön ayar. Uygula, o yuvadaki DPI, rapor hızı, debounce, sensör anahtarları, maksimum performans ve ışık durumunu fareye yazar. Mevcut ayarları buraya kaydet, farenin o anki ayarlarını yuvaya alır; yeniden adlandırılabilir ve varsayılana döndürülebilir."),
        ("dpi", "DPI, imlecin fare hareketine ne kadar hızlı tepki vereceğidir. Kademeler arasında farenin DPI tuşuyla geçilir. Düşük değer oyunda hassas nişan, yüksek değer masaüstünde hızlı gezinme sağlar."),
        ("rate", "Rapor hızı, farenin bilgisayara saniyede kaç kez konum bildirdiğidir. 1000 Hz en akıcı ve en düşük gecikmeli seçenektir; düşük değerler biraz pil kazandırır."),
        ("debounce", "Debounce, iki tıklama arasında geçmesi gereken en kısa süredir. Düşük değer daha hızlı tıklama sağlar; çok düşük değer istemsiz çift tıklamaya yol açabilir. 4 ms iyi bir denge."),
        ("motion", "Motion sync, sensör okumasını rapor zamanına hizalar. Hareket daha tutarlı olur, buna karşılık çok küçük bir gecikme eklenir."),
        ("angle", "Açı düzeltme, yataya veya dikeye yakın hareketleri düz çizgiye zorlar. Oyunda mikro düzeltmeleri bozduğu için genellikle kapalı tutulur."),
        ("ripple", "Ripple kontrolü, yüksek DPI'da sensör titremesini yumuşatır. Gecikme eklediği için oyunda kapalı önerilir."),
        ("perf", "Maksimum performans, sensörü tam güçte tutar ve seçilen süre dolana kadar uyutmaz. İlk harekette takılmayı önler, biraz pil harcar."),
        ("light", "Işık menüsü alt ışık şeridinin modunu, rengini, parlaklığını ve hızını ayarlar. Kapalı tutmak pil ömrünü belirgin biçimde uzatır."),
        ("moveoff", "Hareket ederken ışığı kapat seçeneği, fare kullanılırken ışığı söndürür; ışık yalnızca fare dururken yanar."),
        ("ledoff", "Kapanma süresi, fare hareketsiz kaldıktan ne kadar sonra ışıkların söneceğini belirler."),
        ("dpiled", "DPI gösterge ışığı, aktif DPI kademesinin rengini gösteren küçük ışıktır. Sabit yanabilir ya da yanıp sönebilir."),
        ("longrange", "Uzun menzil modu, alıcı ile fare arasındaki mesafeyi ve parazit direncini artırır; daha fazla pil harcar. Masada, alıcı yakındayken gerekli değildir."),
    ],
    "en": [
        ("battery", "The number on the icon is the battery percentage; a yellow frame means charging. You get a notification when charging starts or stops and at 20% and 10%. While the mouse sleeps the icon turns grey and recovers when you move it."),
        ("presets", "Five editable presets. Apply writes that slot's DPI, report rate, debounce, sensor switches, peak performance and lighting state to the mouse. Save current settings here captures the mouse's current settings into the slot; slots can be renamed and reset to default."),
        ("dpi", "DPI is how fast the cursor reacts to mouse movement. The DPI button on the mouse cycles through the stages. Low values give precise aim in games, high values fast navigation on the desktop."),
        ("rate", "Report rate is how many times per second the mouse reports its position. 1000 Hz is the smoothest and lowest latency option; lower values save a little battery."),
        ("debounce", "Debounce is the shortest time allowed between two clicks. Lower values click faster; very low values can cause accidental double clicks. 4 ms is a good balance."),
        ("motion", "Motion sync aligns the sensor reading with the report timing. Movement becomes more consistent at the cost of a very small delay."),
        ("angle", "Angle snapping forces nearly horizontal or vertical movements into straight lines. It ruins micro adjustments in games, so it is usually kept off."),
        ("ripple", "Ripple control smooths sensor jitter at high DPI. It adds latency, so it is recommended off for gaming."),
        ("perf", "Peak performance keeps the sensor at full power and prevents sleep until the chosen time passes. It avoids a hitch on the first movement and uses a little more battery."),
        ("light", "The lighting menu sets the mode, colour, brightness and speed of the light strip. Keeping it off extends battery life noticeably."),
        ("moveoff", "Lights off while moving turns the lighting off whenever the mouse is in use; it only lights up while the mouse rests."),
        ("ledoff", "The lights off delay sets how long after the mouse stops moving the lighting switches off."),
        ("dpiled", "The DPI indicator light is the small LED that shows the colour of the active DPI stage. It can be steady or flicker."),
        ("longrange", "Long range mode increases the distance and interference resistance between receiver and mouse at the cost of battery. Not needed on a desk with the receiver nearby."),
    ],
    "es": [
        ("battery", "El número del icono es el porcentaje de batería; el marco amarillo indica carga. Recibirás avisos al iniciar o terminar la carga y al 20% y 10%. Si el ratón está en reposo, el icono se vuelve gris y se recupera al moverlo."),
        ("presets", "Cinco preajustes editables. Aplicar escribe en el ratón el DPI, la tasa de sondeo, el antirrebote, los interruptores del sensor, el rendimiento máximo y el estado de la iluminación de ese preajuste. Guardar los ajustes actuales aquí copia la configuración actual del ratón al preajuste; también se puede renombrar y restablecer."),
        ("dpi", "El DPI es la rapidez con la que el cursor responde al movimiento. El botón DPI del ratón alterna entre niveles. Valores bajos dan puntería precisa en juegos; valores altos, navegación rápida en el escritorio."),
        ("rate", "La tasa de sondeo es cuántas veces por segundo el ratón informa su posición. 1000 Hz es la opción más fluida y con menor latencia; valores menores ahorran algo de batería."),
        ("debounce", "El antirrebote es el tiempo mínimo entre dos clics. Valores bajos permiten clics más rápidos; valores muy bajos pueden causar dobles clics accidentales. 4 ms es un buen equilibrio."),
        ("motion", "Motion sync alinea la lectura del sensor con el momento del informe. El movimiento es más consistente a cambio de un retardo mínimo."),
        ("angle", "La corrección de ángulo convierte los movimientos casi horizontales o verticales en líneas rectas. Arruina los microajustes en juegos, así que suele mantenerse apagada."),
        ("ripple", "El control de ondulación suaviza el temblor del sensor a DPI altos. Añade latencia, por lo que se recomienda apagado para jugar."),
        ("perf", "El rendimiento máximo mantiene el sensor a plena potencia y evita el reposo hasta que pase el tiempo elegido. Evita un tirón en el primer movimiento y gasta algo más de batería."),
        ("light", "El menú de iluminación ajusta el modo, el color, el brillo y la velocidad de la tira de luz. Mantenerla apagada alarga bastante la batería."),
        ("moveoff", "Apagar luces al mover apaga la iluminación mientras usas el ratón; solo se enciende cuando está quieto."),
        ("ledoff", "El retardo de apagado define cuánto tiempo después de dejar de mover el ratón se apaga la iluminación."),
        ("dpiled", "La luz indicadora de DPI es el pequeño LED que muestra el color del nivel de DPI activo. Puede ser fija o parpadear."),
        ("longrange", "El modo de largo alcance aumenta la distancia y la resistencia a interferencias entre receptor y ratón a costa de batería. No hace falta en un escritorio con el receptor cerca."),
    ],
    "fr": [
        ("battery", "Le nombre sur l'icône est le pourcentage de batterie ; le cadre jaune indique la charge. Vous êtes prévenu au début et à la fin de la charge, puis à 20% et 10%. Quand la souris est en veille, l'icône devient grise et revient dès que vous la bougez."),
        ("presets", "Cinq préréglages modifiables. Appliquer écrit dans la souris le DPI, le taux de rapport, l'anti rebond, les options du capteur, la performance maximale et l'état de l'éclairage du préréglage. Enregistrer les réglages actuels ici copie la configuration actuelle de la souris dans le préréglage ; on peut aussi le renommer et le rétablir."),
        ("dpi", "Le DPI est la vitesse à laquelle le curseur réagit au mouvement. Le bouton DPI de la souris passe d'un niveau à l'autre. Les valeurs basses donnent une visée précise en jeu, les valeurs hautes une navigation rapide sur le bureau."),
        ("rate", "Le taux de rapport est le nombre de fois par seconde où la souris envoie sa position. 1000 Hz est l'option la plus fluide et la plus réactive ; des valeurs plus basses économisent un peu de batterie."),
        ("debounce", "L'anti rebond est le délai minimal entre deux clics. Une valeur basse permet des clics plus rapides ; une valeur trop basse peut provoquer des doubles clics involontaires. 4 ms est un bon équilibre."),
        ("motion", "Motion sync aligne la lecture du capteur sur l'instant du rapport. Le mouvement est plus régulier au prix d'un délai infime."),
        ("angle", "La correction d'angle transforme les mouvements presque horizontaux ou verticaux en lignes droites. Elle gêne les micro ajustements en jeu, on la laisse donc généralement désactivée."),
        ("ripple", "Le contrôle d'ondulation lisse le tremblement du capteur à haut DPI. Il ajoute de la latence, mieux vaut le désactiver pour jouer."),
        ("perf", "La performance maximale garde le capteur à pleine puissance et empêche la veille jusqu'à la fin du délai choisi. Elle évite un à coup au premier mouvement et consomme un peu plus de batterie."),
        ("light", "Le menu éclairage règle le mode, la couleur, la luminosité et la vitesse de la bande lumineuse. L'éteindre prolonge nettement l'autonomie."),
        ("moveoff", "Éteindre les lumières en mouvement coupe l'éclairage pendant l'utilisation ; il ne s'allume que lorsque la souris est immobile."),
        ("ledoff", "Le délai d'extinction définit combien de temps après l'arrêt de la souris l'éclairage s'éteint."),
        ("dpiled", "Le voyant DPI est la petite LED qui affiche la couleur du niveau de DPI actif. Il peut être fixe ou clignotant."),
        ("longrange", "Le mode longue portée augmente la distance et la résistance aux interférences entre le récepteur et la souris, au prix de la batterie. Inutile sur un bureau avec le récepteur à proximité."),
    ],
    "de": [
        ("battery", "Die Zahl im Symbol ist der Akkustand in Prozent; ein gelber Rahmen bedeutet Laden. Sie werden beim Start und Ende des Ladens sowie bei 20% und 10% benachrichtigt. Im Ruhezustand wird das Symbol grau und erholt sich, sobald Sie die Maus bewegen."),
        ("presets", "Fünf bearbeitbare Voreinstellungen. Anwenden schreibt DPI, Abfragerate, Entprellung, Sensorschalter, maximale Leistung und Beleuchtungszustand der Voreinstellung in die Maus. Aktuelle Einstellungen hier speichern übernimmt die aktuellen Mauseinstellungen in den Speicherplatz; umbenennen und zurücksetzen ist möglich."),
        ("dpi", "DPI bestimmt, wie schnell der Cursor auf Bewegungen reagiert. Die DPI Taste der Maus schaltet zwischen den Stufen um. Niedrige Werte ermöglichen präzises Zielen in Spielen, hohe Werte schnelle Navigation auf dem Desktop."),
        ("rate", "Die Abfragerate gibt an, wie oft pro Sekunde die Maus ihre Position meldet. 1000 Hz ist am flüssigsten und hat die geringste Verzögerung; niedrigere Werte sparen etwas Akku."),
        ("debounce", "Die Entprellung ist die kürzeste erlaubte Zeit zwischen zwei Klicks. Niedrige Werte klicken schneller; zu niedrige Werte können ungewollte Doppelklicks verursachen. 4 ms ist ein guter Kompromiss."),
        ("motion", "Motion Sync richtet die Sensorabfrage am Berichtszeitpunkt aus. Die Bewegung wird gleichmäßiger, bei einer winzigen zusätzlichen Verzögerung."),
        ("angle", "Die Winkelkorrektur zwingt fast waagerechte oder senkrechte Bewegungen auf gerade Linien. Sie stört Mikrokorrekturen in Spielen und bleibt daher meist aus."),
        ("ripple", "Die Ripple Kontrolle glättet Sensorzittern bei hohem DPI. Sie erhöht die Latenz und sollte zum Spielen aus sein."),
        ("perf", "Maximale Leistung hält den Sensor auf voller Kraft und verhindert den Ruhezustand bis zum Ablauf der gewählten Zeit. Das vermeidet ein Ruckeln bei der ersten Bewegung und kostet etwas Akku."),
        ("light", "Das Beleuchtungsmenü regelt Modus, Farbe, Helligkeit und Geschwindigkeit des Leuchtstreifens. Ausgeschaltet hält der Akku deutlich länger."),
        ("moveoff", "Licht bei Bewegung aus schaltet die Beleuchtung während der Nutzung ab; sie leuchtet nur, wenn die Maus ruht."),
        ("ledoff", "Die Abschaltverzögerung legt fest, wie lange nach dem Stillstand der Maus die Beleuchtung ausgeht."),
        ("dpiled", "Das DPI Anzeigelicht ist die kleine LED, die die Farbe der aktiven DPI Stufe zeigt. Sie kann dauerhaft leuchten oder flackern."),
        ("longrange", "Der Langstreckenmodus erhöht Reichweite und Störfestigkeit zwischen Empfänger und Maus auf Kosten des Akkus. Am Schreibtisch mit nahem Empfänger nicht nötig."),
    ],
    "ru": [
        ("battery", "Число на значке это заряд в процентах; жёлтая рамка означает зарядку. Уведомления приходят при начале и завершении зарядки, а также при 20% и 10%. Когда мышь спит, значок становится серым и восстанавливается после движения."),
        ("presets", "Пять редактируемых пресетов. Применить записывает в мышь DPI, частоту опроса, антидребезг, переключатели сенсора, максимальную производительность и состояние подсветки пресета. Сохранить текущие настройки сюда копирует текущие настройки мыши в пресет; его можно переименовать и сбросить."),
        ("dpi", "DPI определяет, насколько быстро курсор реагирует на движение. Кнопка DPI на мыши переключает уровни. Низкие значения дают точное прицеливание в играх, высокие быструю навигацию на рабочем столе."),
        ("rate", "Частота опроса это сколько раз в секунду мышь сообщает позицию. 1000 Гц самый плавный вариант с наименьшей задержкой; меньшие значения немного экономят батарею."),
        ("debounce", "Антидребезг это минимальное время между двумя кликами. Низкие значения ускоряют клики; слишком низкие могут вызвать случайные двойные клики. 4 мс хороший баланс."),
        ("motion", "Motion Sync выравнивает чтение сенсора по моменту отчёта. Движение становится стабильнее ценой крошечной задержки."),
        ("angle", "Выравнивание угла превращает почти горизонтальные или вертикальные движения в прямые линии. Оно мешает микрокоррекции в играх, поэтому обычно выключено."),
        ("ripple", "Контроль ряби сглаживает дрожание сенсора на высоком DPI. Он добавляет задержку, для игр рекомендуется выключить."),
        ("perf", "Максимальная производительность держит сенсор на полной мощности и не даёт уснуть до истечения выбранного времени. Это убирает рывок при первом движении и немного расходует батарею."),
        ("light", "Меню подсветки задаёт режим, цвет, яркость и скорость световой полосы. Выключенная подсветка заметно продлевает работу от батареи."),
        ("moveoff", "Гасить подсветку при движении выключает свет во время использования; он горит только когда мышь неподвижна."),
        ("ledoff", "Задержка выключения определяет, через сколько после остановки мыши гаснет подсветка."),
        ("dpiled", "Индикатор DPI это маленький светодиод, показывающий цвет активного уровня DPI. Может гореть постоянно или мерцать."),
        ("longrange", "Режим дальней связи увеличивает дистанцию и помехоустойчивость между приёмником и мышью ценой батареи. На столе с приёмником рядом не нужен."),
    ],
    "zh": [
        ("battery", "图标上的数字是电量百分比，黄色边框表示正在充电。开始和结束充电以及电量到 20% 和 10% 时会收到通知。鼠标休眠时图标变灰，移动鼠标后恢复。"),
        ("presets", "五个可编辑预设。应用会把该预设的 DPI、回报率、去抖动、传感器开关、最高性能和灯光状态写入鼠标。将当前设置保存到此处会把鼠标当前设置存入该预设；预设可重命名和恢复默认。"),
        ("dpi", "DPI 决定光标对移动的反应速度。鼠标上的 DPI 键在各档位间切换。低数值适合游戏中的精确瞄准，高数值适合桌面上的快速移动。"),
        ("rate", "回报率是鼠标每秒向电脑报告位置的次数。1000 Hz 最流畅、延迟最低；较低数值可略微省电。"),
        ("debounce", "去抖动是两次点击之间允许的最短时间。数值越低点击越快，过低可能导致误双击。4 ms 是较好的平衡。"),
        ("motion", "运动同步让传感器读取与回报时刻对齐。移动更稳定，但会增加极小的延迟。"),
        ("angle", "直线修正会把接近水平或垂直的移动强制修正为直线。它会破坏游戏中的微调，因此通常保持关闭。"),
        ("ripple", "波纹控制可平滑高 DPI 下的传感器抖动。它会增加延迟，游戏时建议关闭。"),
        ("perf", "最高性能让传感器保持全功率，并在所选时间内不进入休眠。可避免首次移动时的卡顿，略微增加耗电。"),
        ("light", "灯光菜单设置灯带的模式、颜色、亮度和速度。关闭灯光可明显延长续航。"),
        ("moveoff", "移动时关闭灯光会在使用鼠标时熄灭灯光，只在鼠标静止时点亮。"),
        ("ledoff", "关灯延时决定鼠标停止移动后多久熄灭灯光。"),
        ("dpiled", "DPI 指示灯是显示当前 DPI 档位颜色的小灯。可以常亮或闪烁。"),
        ("longrange", "远距离模式会增加接收器与鼠标之间的距离和抗干扰能力，但更耗电。接收器在桌面附近时不需要。"),
    ],
    "ja": [
        ("battery", "アイコンの数字はバッテリー残量（%）、黄色の枠は充電中を示します。充電の開始と終了、残量 20% と 10% で通知します。マウスがスリープ中はアイコンが灰色になり、動かすと戻ります。"),
        ("presets", "編集できるプリセットが 5 つあります。適用はそのプリセットの DPI、レポートレート、デバウンス、センサー設定、最高パフォーマンス、ライトの状態をマウスに書き込みます。現在の設定をここに保存はマウスの現在の設定をプリセットに取り込みます。名前の変更と初期化も可能です。"),
        ("dpi", "DPI はカーソルがマウスの動きにどれだけ速く反応するかです。マウスの DPI ボタンで段階を切り替えます。低い値はゲームでの正確な照準、高い値はデスクトップでの素早い移動に向きます。"),
        ("rate", "レポートレートはマウスが 1 秒に何回位置を送信するかです。1000 Hz が最も滑らかで遅延が少なく、低い値はわずかに省電力です。"),
        ("debounce", "デバウンスは 2 回のクリック間に必要な最短時間です。低いほど速くクリックできますが、低すぎると意図しないダブルクリックが起きることがあります。4 ms がよいバランスです。"),
        ("motion", "モーションシンクはセンサーの読み取りをレポートのタイミングに合わせます。動きが安定する代わりに、ごくわずかな遅延が加わります。"),
        ("angle", "角度補正は水平や垂直に近い動きを直線に補正します。ゲームでの微調整を妨げるため、通常はオフにします。"),
        ("ripple", "リップル制御は高 DPI でのセンサーの震えを滑らかにします。遅延が増えるため、ゲームではオフを推奨します。"),
        ("perf", "最高パフォーマンスはセンサーをフル出力に保ち、設定時間が経つまでスリープさせません。最初の動きでの引っかかりを防ぎ、少し電力を使います。"),
        ("light", "ライティングメニューではライトバーのモード、色、明るさ、速度を設定します。オフにするとバッテリーが大幅に長持ちします。"),
        ("moveoff", "移動中はライトを消すをオンにすると、使用中はライトが消え、静止中だけ点灯します。"),
        ("ledoff", "消灯までの時間は、マウスが止まってからライトが消えるまでの時間です。"),
        ("dpiled", "DPI インジケーターは現在の DPI 段階の色を示す小さな LED です。常時点灯または点滅にできます。"),
        ("longrange", "長距離モードはレシーバーとマウスの距離と耐干渉性を高めますが、電力を多く使います。レシーバーが近い机の上では不要です。"),
    ],
    "ko": [
        ("battery", "아이콘의 숫자는 배터리 잔량(%)이고 노란 테두리는 충전 중을 뜻합니다. 충전 시작과 종료, 잔량 20%와 10%에서 알림이 옵니다. 마우스가 절전 중이면 아이콘이 회색이 되고 움직이면 돌아옵니다."),
        ("presets", "편집 가능한 프리셋 5개. 적용은 그 프리셋의 DPI, 폴링 레이트, 디바운스, 센서 옵션, 최고 성능, 조명 상태를 마우스에 씁니다. 현재 설정을 여기에 저장은 마우스의 현재 설정을 프리셋에 담습니다. 이름 바꾸기와 기본값 복원도 가능합니다."),
        ("dpi", "DPI는 커서가 마우스 움직임에 얼마나 빠르게 반응하는지입니다. 마우스의 DPI 버튼으로 단계를 전환합니다. 낮은 값은 게임에서 정밀한 조준에, 높은 값은 데스크톱에서 빠른 이동에 좋습니다."),
        ("rate", "폴링 레이트는 마우스가 초당 몇 번 위치를 보고하는지입니다. 1000 Hz가 가장 부드럽고 지연이 적으며, 낮은 값은 배터리를 조금 아낍니다."),
        ("debounce", "디바운스는 두 클릭 사이에 필요한 최소 시간입니다. 낮을수록 빠르게 클릭할 수 있지만 너무 낮으면 의도치 않은 더블 클릭이 생길 수 있습니다. 4 ms가 적당합니다."),
        ("motion", "모션 싱크는 센서 읽기를 보고 시점에 맞춥니다. 움직임이 더 일정해지는 대신 아주 작은 지연이 생깁니다."),
        ("angle", "각도 보정은 거의 수평이나 수직인 움직임을 직선으로 만듭니다. 게임의 미세 조정을 방해하므로 보통 꺼 둡니다."),
        ("ripple", "리플 제어는 높은 DPI에서 센서 떨림을 부드럽게 합니다. 지연이 늘어나므로 게임에서는 끄는 것을 권장합니다."),
        ("perf", "최고 성능은 센서를 최대 출력으로 유지하고 정해진 시간까지 절전에 들어가지 않게 합니다. 첫 움직임의 끊김을 막고 배터리를 조금 더 씁니다."),
        ("light", "조명 메뉴는 라이트 바의 모드, 색상, 밝기, 속도를 설정합니다. 조명을 끄면 배터리가 눈에 띄게 오래갑니다."),
        ("moveoff", "움직일 때 조명 끄기는 사용 중에 조명을 끄고 마우스가 멈춰 있을 때만 켭니다."),
        ("ledoff", "조명 꺼짐 지연은 마우스가 멈춘 뒤 조명이 꺼지기까지의 시간을 정합니다."),
        ("dpiled", "DPI 표시등은 현재 DPI 단계의 색을 보여 주는 작은 LED입니다. 고정 또는 깜박임으로 설정할 수 있습니다."),
        ("longrange", "장거리 모드는 수신기와 마우스 사이의 거리와 간섭 저항을 높이는 대신 배터리를 더 씁니다. 수신기가 가까운 책상에서는 필요 없습니다."),
    ],
    "ar": [
        ("battery", "الرقم على الأيقونة هو نسبة البطارية، والإطار الأصفر يعني الشحن. تصلك إشعارات عند بدء الشحن وانتهائه وعند 20% و10%. عندما تكون الفأرة في وضع السكون تصبح الأيقونة رمادية وتعود عند تحريكها."),
        ("presets", "خمسة إعدادات مسبقة قابلة للتعديل. تطبيق يكتب إلى الفأرة قيمة DPI ومعدل الاستجابة ومنع الارتداد وخيارات المستشعر والأداء الأقصى وحالة الإضاءة لهذا الإعداد. حفظ الإعدادات الحالية هنا ينسخ إعدادات الفأرة الحالية إلى الإعداد المسبق، ويمكن إعادة تسميته واستعادته."),
        ("dpi", "DPI هو مدى سرعة استجابة المؤشر لحركة الفأرة. زر DPI على الفأرة يبدّل بين المستويات. القيم المنخفضة تمنح تصويباً دقيقاً في الألعاب، والقيم العالية تنقلاً سريعاً على سطح المكتب."),
        ("rate", "معدل الاستجابة هو عدد مرات إبلاغ الفأرة عن موضعها في الثانية. 1000 Hz هو الأكثر سلاسة والأقل تأخيراً، والقيم الأقل توفر قليلاً من البطارية."),
        ("debounce", "منع الارتداد هو أقصر وقت مسموح بين نقرتين. القيم المنخفضة تنقر أسرع، والمنخفضة جداً قد تسبب نقراً مزدوجاً غير مقصود. 4 ms توازن جيد."),
        ("motion", "مزامنة الحركة توائم قراءة المستشعر مع توقيت الإبلاغ. تصبح الحركة أكثر اتساقاً مقابل تأخير ضئيل جداً."),
        ("angle", "تصحيح الزاوية يحوّل الحركات شبه الأفقية أو العمودية إلى خطوط مستقيمة. يفسد التعديلات الدقيقة في الألعاب لذا يبقى مطفأً عادةً."),
        ("ripple", "التحكم في التموج ينعّم اهتزاز المستشعر عند DPI مرتفع. يضيف تأخيراً، لذا يُنصح بإيقافه في الألعاب."),
        ("perf", "الأداء الأقصى يبقي المستشعر بكامل قوته ويمنع السكون حتى انقضاء الوقت المحدد. يتجنب تعثراً عند أول حركة ويستهلك قليلاً من البطارية."),
        ("light", "قائمة الإضاءة تضبط وضع شريط الإضاءة ولونه وسطوعه وسرعته. إبقاؤه مطفأً يطيل عمر البطارية بشكل ملحوظ."),
        ("moveoff", "إطفاء الإضاءة أثناء الحركة يطفئ الإضاءة أثناء الاستخدام، ولا تضيء إلا عندما تكون الفأرة ساكنة."),
        ("ledoff", "مهلة الإطفاء تحدد بعد كم من الوقت من توقف الفأرة تنطفئ الإضاءة."),
        ("dpiled", "مؤشر DPI هو الضوء الصغير الذي يعرض لون مستوى DPI النشط. يمكن أن يكون ثابتاً أو وامضاً."),
        ("longrange", "وضع المدى البعيد يزيد المسافة ومقاومة التداخل بين المستقبل والفأرة مقابل استهلاك أكبر للبطارية. غير ضروري على المكتب مع وجود المستقبل قريباً."),
    ],
}
